version: '3'

services:
  Frontend:
    image: csw1511/neureka-frontend
    ports:
      - "5174:5174"
    restart: always

  Backend:
    image: csw1511/neureka-backend
    ports:
      - "8080:8080"
    restart: always

  Python:
    image: csw1511/neureka-python
    ports:
      - "8000:8000"
    restart: always